#
# Get Listener Port by Port Number
#
# Input vars:
# - apigwMgmtEndpoint
# - apigwUser
# - apigwPassword
# - portNumber
#
# Output vars:
# - apigw_response_get_port_by_number
#

- name: "get target listener port by number"
  uri:
    url: '{{ apigwMgmtEndpoint }}/restman/1.0/listenPorts?port={{ portNumber }}'
    method: GET
    force_basic_auth: yes
    user: "{{ apigwUser }}"
    password: "{{ apigwPassword }}"
    headers:
      Content-Type: 'application/xml'
    validate_certs: no
    status_code: 200
    return_content: yes
  register: apigw_response_get_port_by_number
