#
# Get Private Key
#
# Input vars:
# - apigwMgmtEndpoint
# - apigwUser
# - apigwPassword
# - keyAlias
# Output vars:
# - apigw_response_get_privatekey
#

- name: "lookup private key"
  uri:
    url: '{{ apigwMgmtEndpoint }}/restman/1.0/privateKeys/00000000000000000000000000000002:{{ keyAlias | mandatory | urlencode}}'
    method: GET
    force_basic_auth: yes
    user: "{{ apigwUser }}"
    password: "{{ apigwPassword }}"
    headers:
      Content-Type: 'application/xml'
    validate_certs: no
    status_code: 200,404
    return_content: yes
  register: apigw_response_get_privatekey

