#
# Get Listener Port by Port Name
#
# Input vars:
# - apigwMgmtEndpoint
# - apigwUser
# - apigwPassword
# - portName
#
# Output vars:
# - apigw_response_get_port_by_name
#

- name: "get target listener port by name"
  uri:
    url: '{{ apigwMgmtEndpoint }}/restman/1.0/listenPorts?name={{ portName | urlencode }}'
    method: GET
    force_basic_auth: yes
    user: "{{ apigwUser }}"
    password: "{{ apigwPassword }}"
    headers:
      Content-Type: 'application/xml'
    validate_certs: no
    status_code: 200
    return_content: yes
  register: apigw_response_get_port_by_name
