#
# Import Private Key
#
# Input vars:
# - apigwMgmtEndpoint
# - apigwUser
# - apigwPassword
# - keyAlias
# - keyPayload
# Output vars:
# - apigw_response_import_privatekey
#

- name: "import private key"
  uri:
    url: "{{ apigwMgmtEndpoint }}/restman/1.0/privateKeys/00000000000000000000000000000002:{{ keyAlias | urlencode }}/import"
    method: POST
    force_basic_auth: yes
    user: "{{ apigwUser }}"
    password: "{{ apigwPassword }}"
    headers:
      Content-Type: 'application/xml'
    body: "{{ keyPayload }}"
    validate_certs: no
    status_code: 200,201
    return_content: yes
  register: apigw_response_import_privatekey
  changed_when: apigw_response_import_privatekey is succeeded

