#
# Set service active version comment
#
# Input vars:
# - apigwMgmtEndpoint
# - apigwUser
# - apigwPassword
# - serviceId
# - versionComment
# Output vars:
# - apigw_response_set_service_active_version_comment
#
- name: "Set service active version comment to {{ versionComment }}"
  uri:
    url: '{{ apigwMgmtEndpoint }}/restman/1.0/services/{{ serviceId }}/versions/active/comment'
    method: PUT
    force_basic_auth: yes
    user: "{{ apigwUser }}"
    password: "{{ apigwPassword }}"
    headers:
      Content-Type: 'application/xml'
    validate_certs: no
    body: "{{ versionComment }}"
    status_code: 200
    return_content: yes
  register: apigw_response_set_service_active_version_comment
  changed_when: apigw_response_set_service_active_version_comment is succeeded
