#
# Update Policy Manager user password - the target user must exist
#
# Input vars:
# - apigwMgmtEndpoint
# - apigwUser (used for connecting to the Gateway)
# - apigwPassword (used for connecting to the Gateway)
# - username  (the user account to be updated)
# - password  (new password)
# Output vars:
# - apigw_response_update_password
#

- name: "Validate user {{ username }} exists on target Gateway"
  include_tasks: getUserByName.yml

- name: "parse lookup result"
  delegate_to: localhost
  connection: local
  # can have zero or one result
  failed_when: false
  xml:
    xmlstring: "{{ apigw_response_get_user_by_name.content }}"
    namespaces:
      l7: "http://ns.l7tech.com/2010/04/gateway-management"
    xpath: /l7:List/l7:Item/l7:Id
    content: text
  register: xmlResult

- name: "Fail if user does not exist"
  fail:
    msg: "ERROR - the arget user {{ username }} must exist on the target Gateway"
  when:
    - xmlResult.count is not defined

- name: "Update password of user {{ username }}"
  uri:
    url: "{{ apigwMgmtEndpoint }}/restman/1.0/users/{{ xmlResult.matches[0] | json_query('*') | json_query('[0]') }}/password"
    method: PUT
    force_basic_auth: yes
    user: "{{ apigwUser }}"
    password: "{{ apigwPassword }}"
    headers:
      Content-Type: 'application/xml'
    validate_certs: no
    body: '{{ password }}'
    status_code: 200,201
    return_content: yes
  register: apigw_response_update_password
  changed_when: apigw_response_update_password is succeeded

