######## Play 1: setup inventory ########

- hosts: localhost
  connection: local
  gather_facts: no
  roles:
  - role: ../../roles/generic_addHosts
    vars:
      consulKeyPath: "https://ecomm.fm.rbsgrp.net/v1/kv/application/nwm/{{ awsEnv | mandatory }}/terraform/core/outputs/agilemarkets/{{ awsRegion | mandatory }}/apigw_instances_private_ip?raw"
      groupName: apigw
 
######## Play 2: configura API Gateway ########
- hosts: apigw
  vars_files:
  - ../../vars_files/apigw
  - files/config/{{ 'nonprod' if awsEnv != 'prod' else 'prod' }}.yml
  remote_user: "{{ remoteUser }}"
  gather_facts: yes
  vars:
    updatePrivateKey: false
    listenPortExists: false
    forceUpdate: false
  tasks:
  - name: "retrieve password from Consul"
    block:
    - name: "check for consul token"
      set_fact:
        consulTokenPassword: "{{ lookup('env','CONSUL_HTTP_TOKEN') }}"
      when: consulTokenPassword is not defined 
    - fail:
        msg: "ERROR: Valid consul token required in either env var 'CONSUL_HTTP_TOKEN' or as input var 'consulTokenPassword'"
      when: consulTokenPassword == ""
    - name: "lookup initial password in Consul"
      uri:
        url: "https://ecomm.fm.rbsgrp.net/v1/kv/application/nwm/{{ awsEnv | mandatory }}/terraform/core/outputs/agilemarkets/{{ awsRegion | mandatory }}/apigw_initial_password?raw"
        headers:
          X-Consul-Token: "{{ consulTokenPassword }}"
        status_code: 200
        return_content: true
      register: consulOutputPassword
    - name: "set initial password"
      set_fact:
        apigwPassword: "{{ consulOutputPassword.content }}"
    - debug: var=apigwPassword
    when: apigwPassword is not defined 
    delegate_to: localhost
    connection: local
    run_once: true

  - name: "Block: main()"
    # The private key is base64 encoded string of a password protected PFX cert
    block: 
    - include_tasks: tasks/setupListenerPort.yml
      vars:
        portName: "{{ item.portName }}"
        portNumber: "{{ item.portNumber }}"
        serviceName: "{{ item.serviceName }}"
        keyAlias: "{{ item.portName }}"
      loop: "{{ fxmpListenerPortConfiguration }}"
      when: targetPortNumber is not defined or targetPortNumber == item.portNumber

  - name: "Block: Health Check"
    block:
    - name: "check target port"
      include_role: 
        name: ../../roles/generic_healthCheck
      vars:
        thePort: "{{ item.portNumber }}"
      loop: "{{ fxmpListenerPortConfiguration }}"
      when: targetPortNumber is not defined or targetPortNumber == item.portNumber
    - name: "Child task: check gateway health"
      include_tasks: tasks/runHealthChecks.yml

